/**
 ******************************************************************************
 * @file    main_app.c
 * @brief   VCI Gateway — Application entry point
 ******************************************************************************
 *  This file is the application-level main (called from CubeMX main.c after
 *  all HAL and peripheral initialisation is complete).
 *
 *  CubeMX main.c should call:
 *    extern void VCI_AppMain(void);
 *    VCI_AppMain();        // after all MX_xxx_Init() calls
 *
 *  Peripherals initialised by CubeMX (HAL drivers):
 *    FDCAN1, FDCAN2  — configured in CubeMX, HAL handles provided
 *    USART2          — LIN (LIN mode enabled)
 *    USART3          — K-Line (normal UART, half-duplex)
 *    USB_OTG_HS      — CDC device class
 *    ETH             — RMII, LAN8742A PHY
 *    TIM2            — 1 µs free-running counter for timestamps
 */

#include "main_app.h"
#include "vci_config.h"
#include "rtos_tasks.h"
#include "bus_manager.h"

/* ── Weak symbols — override in application if needed ────────────────── */
__attribute__((weak)) void VCI_BoardEarlyInit(void) {}
__attribute__((weak)) void VCI_BoardLateInit(void)  {}

/* ════════════════════════════════════════════════════════════════════════
 *  VCI_AppMain
 * ════════════════════════════════════════════════════════════════════════ */
void VCI_AppMain(void)
{
    /* Board-specific early init (LED, debug UART, power rails) */
    VCI_BoardEarlyInit();

    /* ── Kernel init ──────────────────────────────────────────────────── */
    if (osKernelInitialize() != osOK) {
        /* Cannot recover — trap in debug */
        for (;;) {}
    }

    /* ── Create all RTOS objects (queues, mutexes, events) ────────────── */
    if (RTOS_CreateAllObjects() != VCI_OK) {
        for (;;) {}
    }

    /* ── Bus Manager init ─────────────────────────────────────────────── */
    BusMgr_Init();

    /* ── Launch all tasks ─────────────────────────────────────────────── */
    if (RTOS_LaunchAllTasks() != VCI_OK) {
        for (;;) {}
    }

    VCI_BoardLateInit();

    /* ── Start scheduler (never returns) ─────────────────────────────── */
    if (osKernelStart() != osOK) {
        for (;;) {}
    }
}


/* ════════════════════════════════════════════════════════════════════════
 *  USB CDC callbacks (called from USB interrupt context)
 * ════════════════════════════════════════════════════════════════════════ */
#include "usbd_cdc_if.h"   /* generated by CubeMX USB CDC middleware     */

/**
 * @brief  Called by USB stack when PC sends data to the device
 *         Runs in USB interrupt context — keep it short!
 */
void VCI_USB_CDC_RxCallback(uint8_t *buf, uint32_t len)
{
    /* Parse the VCI frame header and push request to diag queue         */
    if (len < 4) return;
    if (buf[0] != 0xAAU) return;   /* Missing SYNC byte                  */

    uint16_t payload_len = (uint16_t)((buf[1] << 8) | buf[2]);
    if (payload_len + 4U > len) return;

    VCI_Message_t msg;
    msg.type        = (VCI_MsgType_t)buf[3];
    msg.src_bus     = BUS_ID_USB;
    msg.dst_bus     = BUS_ID_FDCAN1;  /* Default target                 */
    msg.payload_len = (uint16_t)payload_len;
    if (payload_len > sizeof(msg.payload.raw))
        payload_len = sizeof(msg.payload.raw);
    memcpy(msg.payload.raw, &buf[4], payload_len);

    /* Route to diagnostic queue or gateway output */
    if (msg.type == MSG_TYPE_UDS || msg.type == MSG_TYPE_ISOTP) {
        osMessageQueuePut(g_q_diag_req, &msg, 0, 0);
    } else {
        osMessageQueuePut(g_q_gateway_out, &msg, 0, 0);
    }
}

/**
 * @brief  Called when USB CDC is connected/configured
 */
void VCI_USB_CDC_ConnectCallback(void)
{
    osSemaphoreRelease(g_sem_usb_ready);
    osEventFlagsSet(g_evf_system, EVF_USB_CONNECT);
}

void VCI_USB_CDC_DisconnectCallback(void)
{
    osEventFlagsSet(g_evf_system, EVF_USB_DISCONNECT);
}

/* ════════════════════════════════════════════════════════════════════════
 *  Ethernet link callbacks (called from ETH IRQ)
 * ════════════════════════════════════════════════════════════════════════ */


void VCI_ETH_LinkCallback(bool link_up)
{
    if (link_up) {
        osSemaphoreRelease(g_sem_eth_link);
        osEventFlagsSet(g_evf_system, EVF_ETH_LINK_UP);
    } else {
        osEventFlagsSet(g_evf_system, EVF_ETH_LINK_DOWN);
    }
}

/* ════════════════════════════════════════════════════════════════════════
 *  µs timestamp (uses TIM2 running at 1 MHz)
 * ════════════════════════════════════════════════════════════════════════ */
uint32_t VCI_GetTimestampUs(void)
{
    extern TIM_HandleTypeDef htim2;
    return __HAL_TIM_GET_COUNTER(&htim2);
}
